targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          generate_values_in_copy_with: true
          named_parameters: true
          named_parameters_always_required: false

